# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.14.1 on Wed Jul  3 22:42:55 2024
# Model: Coastal Blue Carbon

import logging
import sys

import natcap.invest.coastal_blue_carbon.coastal_blue_carbon
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'analysis_year': '',
    'biophysical_table_path': 'C:\\ELS\\Python3Script\\Adhoc\\JIAKnimepy3\\CoastalBlueCarbon\\outputs_preprocessor\\biophysical_table_sample.csv',
    'discount_rate': '5',
    'do_economic_analysis': True,
    'inflation_rate': '',
    'landcover_snapshot_csv': 'C:\\ELS\\Python3Script\\Adhoc\\JIAKnimepy3\\CoastalBlueCarbon\\inputs\\snapshots.csv',
    'landcover_transitions_table': 'C:\\ELS\\Python3Script\\Adhoc\\JIAKnimepy3\\CoastalBlueCarbon\\outputs_preprocessor\\transitions_sample.csv',
    'price': '',
    'price_table_path': 'C:\\ELS\\Python3Script\\Adhoc\\JIAKnimepy3\\CoastalBlueCarbon\\inputs\\Price_table_SCC_5.csv',
    'results_suffix': '',
    'use_price_table': True,
    'workspace_dir': 'C:\\ELS\\Python3Script\\Adhoc\\JIAKnimepy3\\forProTest',
}

if __name__ == '__main__':
    natcap.invest.coastal_blue_carbon.coastal_blue_carbon.execute(args)
